default: true

MD003:
  style: atx_closed

MD007:
  indent: 4

MD010: false

MD013:
  line_length: 120
  code_blocks: false
  tables: false
  headings: true

MD033:
  allowed_elements:
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6
    - blockquote
    - a
    - code
    - pre
    - em
    - strong
    - ul
    - ol
    - li
    - p
    - hr
    - img
    - table
    - tr
    - th
    - td
    - thead
    - tbody
    - tfoot
    - details
    - summary
    - br
    - mark
    - small
    - sub
    - sup
    - abbr
    - time
    - var
    - s
    - u
    - kbd
    - wbr
    - b
    - span
