name: Markdown Lint (CLI2)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
          config: '.markdownlint-cli2.jsonc'  # Optional, if you have a custom config