name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'
  pull_request:
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          globs: '**/*.md'
