name: Markdown Linter

on:
  push:
    branches: [main, design/file-structure]
  pull_request:
    branches: [main, design/file-structure]

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          globs: '**/*.md'